FROM node:18-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Define build args for client-side
ARG NEXT_PUBLIC_DB_API_KEY
ARG NEXT_PUBLIC_DB_AUTH_DOMAIN
ARG NEXT_PUBLIC_DB_PROJECT_ID
ARG NEXT_PUBLIC_DB_STORAGE_BUCKET
ARG NEXT_PUBLIC_DB_MESSAGING_SENDER_ID
ARG NEXT_PUBLIC_DB_APP_ID
ARG NEXT_PUBLIC_DB_MEASUREMENT_ID

ENV NEXT_PUBLIC_DB_API_KEY=$NEXT_PUBLIC_DB_API_KEY
ENV NEXT_PUBLIC_DB_AUTH_DOMAIN=$NEXT_PUBLIC_DB_AUTH_DOMAIN
ENV NEXT_PUBLIC_DB_PROJECT_ID=$NEXT_PUBLIC_DB_PROJECT_ID
ENV NEXT_PUBLIC_DB_STORAGE_BUCKET=$NEXT_PUBLIC_DB_STORAGE_BUCKET
ENV NEXT_PUBLIC_DB_MESSAGING_SENDER_ID=$NEXT_PUBLIC_DB_MESSAGING_SENDER_ID
ENV NEXT_PUBLIC_DB_APP_ID=$NEXT_PUBLIC_DB_APP_ID
ENV NEXT_PUBLIC_DB_MEASUREMENT_ID=$NEXT_PUBLIC_DB_MEASUREMENT_ID

RUN npm run build

FROM node:18-alpine AS runner

WORKDIR /app

COPY --from=builder /app/.next ./.next
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/public ./public

RUN npm install --production

EXPOSE 3000

CMD ["npm", "start"]
